<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="SalesforceApp" tests="6" time="21.615" ignored="0" failures="0" timestamp="22 Mar 2019 05:12:07 GMT" skipped="3" hostname="DESKTOP-9EBC1DI" errors="1">
  <testcase name="logOutFrmApp" time="0.000" classname="SalesforceApp">
    <skipped/>
  </testcase> <!-- logOutFrmApp -->
  <testcase name="loginTest" time="6.391" classname="SalesforceApp"/>
  <testcase name="profileSettings" time="0.000" classname="SalesforceApp">
    <skipped/>
  </testcase> <!-- profileSettings -->
  <testcase name="closeDialogue" time="1.559" classname="SalesforceApp">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at MainClass.click(MainClass.java:117)
	at SalesforceApp.closeDialogue(SalesforceApp.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- closeDialogue -->
  <testcase name="clickUsrNavButton" time="0.000" classname="SalesforceApp">
    <skipped/>
  </testcase> <!-- clickUsrNavButton -->
  <testcase name="logIn" time="13.665" classname="SalesforceApp"/>
</testsuite> <!-- SalesforceApp -->
